language: java
jdk:
- oraclejdk8
addons:
  ssh_known_hosts:
  - 206.81.15.174
branches:
  only:
  - master
  - develop
script:
- mvn clean package -DskipTests=true
before_install:
- openssl aes-256-cbc -K $encrypted_68de6c0518f2_key -iv $encrypted_68de6c0518f2_iv
  -in cicd-peta.pem.enc -out cicd-peta.pem -d
- chmod 600 cicd-peta.pem

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then ./deploy.sh; fi
